#!/bin/sh /etc/rc.common

USE_PROCD=1

START=90
STOP=15

NAME=aliyundrive-webdav

uci_get_by_type() {
	local ret=$(uci get $NAME.@$1[0].$2 2>/dev/null)
	echo ${ret:=$3}
}

start_service() {
	local refresh_token=$(uci_get_by_type aliyun refresh_token)
	local auth_user=$(uci_get_by_type server auth_user)
	local auth_password=$(uci_get_by_type server auth_password)
	local read_buf_size=$(uci_get_by_type server read_buffer_size 10485760)
	local host=$(uci_get_by_type server host 127.0.0.1)
	local port=$(uci_get_by_type server port 8080)

	procd_open_instance
	procd_set_param command /bin/sh -c "/usr/bin/$NAME --host $host --port $port -S $read_buf_size >>/var/log/$NAME.log 2>&1"
	procd_set_param pidfile /var/run/$NAME.pid
	procd_set_param env REFRESH_TOKEN="$refresh_token"
	[[ ! -z "$auth_user" ]] && procd_set_param env WEBDAV_AUTH_USER="$auth_user"
	[[ ! -z "$auth_password" ]] && procd_set_param env WEBDAV_AUTH_PASSWORD="$auth_password"
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger "/etc/config/$NAME"
}
